# @package _global_
# https://hydra.cc/docs/configure_hydra/intro/

# Remove Hydra logging

defaults:
  - _self_
  - override /hydra/hydra_logging: disabled
  - override /hydra/job_logging: disabled

hydra:
  output_subdir: nulls
  run:
    dir: .
