FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04

#  set variable here


ENV DEBIAN_FRONTEND=noninteractive
RUN : \
    && apt-get update \
    && apt-get update \
    && apt-get install -y --no-install-recommends software-properties-common \
    && apt-get install -y bash ffmpeg libsm6 libxext6 wget git tmux vim nano \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && :

RUN apt-get install build-essential

# Install miniconda
ENV CONDA_DIR /opt/conda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda

# Put conda in path so we can use conda activate
ENV PATH=$CONDA_DIR/bin:$PATH
RUN conda init bash
RUN conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main && \
    conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r
RUN conda create --name myenv python=3.8 -y





# Set up Oh My Tmux
# RUN git clone --single-branch --branch master https://github.com/gardiens/.tmux.git ~/tmux_repo/ \
#   && mkdir -p ~/.config/tmux \
#   && ln -s -f ~/tmux_repo/.tmux.conf ~/.tmux.conf \
#   && cp ~/tmux_repo/.tmux.conf.local ~/.tmux.conf.local

# Make RUN commands use the new environment:
SHELL ["conda", "run", "-n", "myenv", "/bin/bash", "-c"]
#* From now on, every RUN will be run into myenv

#COPY and get into the env
WORKDIR /workspaces/$name_repo

# set the solver to libmamba to be faster
RUN conda update -n base conda -y
RUN conda install -n base conda-libmamba-solver -y
RUN conda config --set solver libmamba

# install pytorch
RUN CUDA_VERSION=$(nvcc --version | grep "release" | sed 's/.*release //' | sed 's/,.*//') && \
    if [ "$CUDA_VERSION" = "11.4" ]; then \
        conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch -y; \
    elif [ "$CUDA_VERSION" = "11.6" ]; then \
        conda install pytorch==1.13.1 torchvision==0.14.1 pytorch-cuda=11.6 -c pytorch -c nvidia -y; \
    elif [ "$CUDA_VERSION" = "12.1" ]; then \
        conda install -n spt pytorch==2.2.0 torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia -y; \
        pip3 install torch torchvision torchaudio; \
    elif [ "$CUDA_VERSION" = "12.0" ]; then \
        conda install pytorch==2.2.0 torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia; \
    elif [ "$CUDA_VERSION" = "11.8" ]; then \
        conda install pytorch==2.2.0 torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia -y ; \
        pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118; \
    else \
        CUDA_MAJOR=$(echo ${CUDA_VERSION} | sed 's/\..*//') && \
        CUDA_MINOR=$(echo ${CUDA_VERSION} | sed 's/.*\.//') && \
        conda install pytorch torchvision torchaudio pytorch-cuda=${CUDA_MAJOR}${CUDA_MINOR} -c pytorch -c nvidia -y; \
    fi




RUN echo 'conda deactivate' >> /root/.bashrc
RUN echo 'conda activate myenv' >> /root/.bashrc



# Install dev dependencies
# RUN pip install pre-commit

# RUN pre-commit install

# # install required packages
# install stm4 dependency
RUN apt-get update
RUN apt-get install -y libtiff-dev libpng-dev libwebp-dev
COPY requirements.txt .
COPY dev_requirements.txt .
RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    g++ \
    python3-dev
RUN python -m pip install --upgrade pip setuptools wheel


RUN python -m pip install Cython 

RUN pip install -r requirements.txt --no-build-isolation


# install dev requirements
RUN pip install -r  dev_requirements.txt  --no-build-isolation

# Setup a non-root user
ARG USERNAME=user1
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    #
    # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME
# add conda to the user
# Set bash as default shell
SHELL ["/bin/bash", "-c"]
RUN chsh -s /bin/bash $USERNAME
USER $USERNAME

RUN echo 'conda deactivate' >> /root/.bashrc
RUN echo 'conda activate myenv' >> /root/.bashrc