defaults:
  - _self_
  - experiments: debug.yaml

task_name: Random_name

seed: 42

# set False to skip model training
train: True
# evaluate on test set, using best model weights achieved during training
test: True
