name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, "release/*"]

jobs:
  run_tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.8"]

    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: install torch
        run : |
          pip install --pre torch torchvision torchaudio
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install sh
          pip install pytest-cov

      - name: List dependencies
        run: python -m pip list

      - name: Run tests
        run: |
          FULL_TEST=1 pytest --cov --cov-report=xml
        shell: bash
        timeout-minutes: 5

      # - name: Upload coverage
      #   uses: codecov/codecov-action@v2
      #   with:
      #     fail_ci_if_error: false